<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wok_gpxviewer"
 *
 * Auto generated by Extension Builder 2021-10-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'GPXViewer',
    'description' => 'Extension with plugin for GPXViewer content element based on GPXViewer from Jürgen Berkemeier (https://www.j-berkemeier.de/GPXViewer/)',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'stable',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
